### ISSUE TITLE
random color issues

### ISSUE THREAD

**Issue by Crash82** [Shakesbeard/com.sdn.lifx-lan2#1]
I found a minor issue if I set it to give it a random color it will remain unchanged

**Comment by Shakesbeard** [comment]
@Crash82 Well. It would have been a miracle if there was no bug at all :D - I have not used that flowcard myself anywhere. It is autogenerated for all light devices with color support. However, I can confirm that this is not working in v0.8.0 as well. I will look into it.

**Comment by Shakesbeard** [comment]
@Crash82 After testing this I can confirm that it actually is not a bug. The card works as expected. However, maybe not like the user would expect it. 
The color is changed but the saturation is not automatically changed. If you change the saturation as well you can see that the color is changing.

**Comment by Shakesbeard** [comment]
I will add this info the the new troubleshooting section in the app info/readme.txt page coming with the next release:

Problem: "Set Random Color" does not seem to set a color.
Reason: The card is autogenerated by Homey and sets a new hue value only.
Solution: Add a "Set Saturation" card in addition to make the color visible.

**Comment by Crash82** [comment]
Thanks for the information it works

 keep up the Good Work
